### ISSUE TITLE
User can view featured recipe

### ISSUE THREAD

**Issue by wang-morris** [wang-morris/ajax-project#1]
## ⚙️ Motivation

User will want to get a recipe recommendation if they are feeling undecided.

## 📐 Plan

The homepage of the app will get data from themealdb API which can look up a random meal on load.

## 🖼️ Wireframes
mobile (https://www.figma.com/file/BOyYUv23HgmZ3nTC7FNTO2/Morris-W---AJAX-Project?node-id=243%3A2497)
desktop (https://www.figma.com/file/BOyYUv23HgmZ3nTC7FNTO2/Morris-W---AJAX-Project?node-id=240%3A2352)

## ✅ Task List

- [x] Create an index.html and styles.css file and create the proper app heading design 
- [x] create a 'image-container' element to hold the img and meal title 
- [x] add an img placeholder as well as text placeholder below it for the featured meal image and name
- [x] create a text box that is able to list the ingredients and the directions of the featured recipe
        The textbox should include a scrollbar for longer lists
- [x] Add a <button> element for adding recipe to favorites, this will have no functionality for now
- [x] Create the menu design for mobile and for the desktop version, ensuring all those buttons are clickable as well
        These icons will not have functionality at this time either
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Open a main.js file 
- [x] Query the DOM for the 'image-container' element
- [x] Listen for the 'load' event 
- [x] send() a request to www.themealdb.com/api/json/v1/1/random.php to get a random meal 
- [x] append() the given data to the 'image-container' element 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
